name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to SSH server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 160.153.175.21
        username: trobits
        password: 3MSbAx39Gb$kVi
        command_timeout: 200m
        script: |
          sudo systemctl start ssh
          cd ../..
          cd /var/www/newsisiku-frontend
          git pull origin main
          npm install
          npm run build
          pm2 restart 1
