name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to SSH server
      uses: appleboy/ssh-action@master
      with:
        host: 160.153.175.21
        username: trobits
        key: -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
          NhAAAAAwEAAQAAAgEAqffYsktiqq4stQ9mvuAit+1r39cYTmnYPdd7J5ZejQgyGk19ZsXz
          k+nE6rCkvz1p7Kz5wekIah4u32eh/dJosBJ4MsVpDIrRp7B0YhPFu3hIM3m6wXLB5l5o38
          UvpZEhvv2lUGZ6JmEO28NPMfDFQweOycnBecSl10qviCm1hnxh46b4HOZ7i5Kv4Hftton7
          fpFjhCeUv5wJ7edehJI831gfIfDIyvTZPunNUr0E2mtK3DWeOyaO24COa0T9irncxq8JFl
          zcuE1PJe7aZmN16E4Gngw/Ho24YmNphscJ7iIrg5CXwN+55dtH2lPTH14MKetLhrGsw7HI
          uTsPDsAoJ1fBnGTR4L3WARoweHDFJqHL6l5KqsmlpkXrj+S+NdTOCy6MmAJB7nvmzHOR6w
          aOgDbgC+phmnATEzYz0YXJdD30edXgkjNSIwAUMjpejgglL2vLJhY4+DoAyZdFsBEygnKM
          tVGUT5+AnIOUtffwseS3DpsGm23xjFOvmQOA6fGOqnZ/hFMvXqq/pH3qV4CG/reh2VBJyt
          fL8TkTRLrDRP1eT7k4AxyOT+yDLc8hkqKvMX0FSPfqU11KvhqlFpZ6s1/H+zdbKLmvvUeh
          d4U34v/5nYo/UuyytUuKveEl7cSAd5qeH8Yc63HIVtGGESiOdgFiz3EKmVzq3rq5JvL5Pl
          UAAAdYH29ZXB9vWVwAAAAHc3NoLXJzYQAAAgEAqffYsktiqq4stQ9mvuAit+1r39cYTmnY
          Pdd7J5ZejQgyGk19ZsXzk+nE6rCkvz1p7Kz5wekIah4u32eh/dJosBJ4MsVpDIrRp7B0Yh
          PFu3hIM3m6wXLB5l5o38UvpZEhvv2lUGZ6JmEO28NPMfDFQweOycnBecSl10qviCm1hnxh
          46b4HOZ7i5Kv4Hftton7fpFjhCeUv5wJ7edehJI831gfIfDIyvTZPunNUr0E2mtK3DWeOy
          aO24COa0T9irncxq8JFlzcuE1PJe7aZmN16E4Gngw/Ho24YmNphscJ7iIrg5CXwN+55dtH
          2lPTH14MKetLhrGsw7HIuTsPDsAoJ1fBnGTR4L3WARoweHDFJqHL6l5KqsmlpkXrj+S+Nd
          TOCy6MmAJB7nvmzHOR6waOgDbgC+phmnATEzYz0YXJdD30edXgkjNSIwAUMjpejgglL2vL
          JhY4+DoAyZdFsBEygnKMtVGUT5+AnIOUtffwseS3DpsGm23xjFOvmQOA6fGOqnZ/hFMvXq
          q/pH3qV4CG/reh2VBJytfL8TkTRLrDRP1eT7k4AxyOT+yDLc8hkqKvMX0FSPfqU11Kvhql
          FpZ6s1/H+zdbKLmvvUehd4U34v/5nYo/UuyytUuKveEl7cSAd5qeH8Yc63HIVtGGESiOdg
          Fiz3EKmVzq3rq5JvL5PlUAAAADAQABAAACABDmpwrVoa5IqwPnD+eviGxDJMypig50Cm9d
          z654TpcWB0tjxLI1QVsGLhFLNtqYXAHPkndEeZR5w13uI2bGpyfI8mBUDnXTkPTsgConfq
          w9Ueqicl5dj6fdX+7OYAZF5/XiqW9U/VT3Jj/WjDeyUh8v73QjxoQZ+Iavs8Qlp5oDoMU/
          G2FeTs8qayg2LLJPxq0Hfn6L5Afol3krXlPu6bQowlHA7Gp4DekqXQMa7hJdBGDgyQbnNu
          HfRuomPlLu1+P+0DfDzKPb9iCWv2tafQU4SwKow5cBbyIDciEXhiaCidKnjFt+s7DGTP8K
          Ak6Wbr21Wrl+TehYs5WtqHnmRCe53XZgd+8yuKDj5wRh91YcSSj5Hc9O05igU7xSa1+6py
          qByWButw7g2YmxQXO0WTwovYQMqXTfVxg/xlKuxJ6/lgkjXcpDEi3h5suErODBbgDWg70C
          F+lU5uA3XfvXkXT6/ZvZLH7ER5VvPvAdpj5XYJXjG6x6cKNsjCDStFuLiBeUIta6pfyC1r
          kbBzHf9LZfR7DnS2VYBLISYpDE/PeHWyaThWHp5U/mXGxrmBZ9SplaMj/A4Eg8ulAX5h4g
          mf2RCzTgvG652YikK5dSBc//VYO2GJt85RHXgDWubqOaJCRJU0XKii1CNkCa1+jYVKym+d
          09N8bajd3arruz7Qh5AAABAQCuv1KfZUyTt/Z8yOtB0qV0TTx024lxWqVdsDqIk2id2hws
          H3YI9E7u4asYC3GvOmjbBjjZzrnG/C95rmsrBxI2iBMGdmtP6+j2nf+VBlXaHtWwM2wcrW
          FXWpE9B11qMntqrMTdB7VGo9hX3k72QL/6WLPeeDjM/1eMe/FplXCPibKatT2kjn9eUXGL
          fNOHCiZj8pgCiADr5ubtWEckcjzHH/0BV9irTS4ltDTjs88A/5WGvqj9Z6RkzMLXhEYwx3
          6+wsKtOA2h6vIqnUqqcvX1QkXcB7nHwHvbbWSZfTopk48whrsOxPMsdJ7NEqY11SN/GFTt
          SnlsFOiHjqH0VFllAAABAQDMmmtl/RckFuLVMrH/cDSxSuXreuy8lrqExAjyBK+E6m9dJC
          0Cop0WwbCQm1o7Ey+4Hy3Q2neyb0gMsBdfOtvx61iS7+upUy/ubkhVKNRnPuIhc3tPe6ZD
          lZKLl0acE1wmJgGDJoIkQEB7fpzWltviZ/VGjFXuWcFtaOcmovFRcJXZ8J+Xg8KjfPjsxd
          CkQIPRLIKxuHmfw/ZjtMhM3TDYcUj8Axt8MY1xk6Lfm0sBp81Ypft8yt553gFdqq0TnXhw
          IJrxzsgcSKS0ZRbBdr8DVlJTxTfOrUHh/nkmWCzqpivItV1XjpkPk2ZzbyA38g8erd0EIE
          TwQjzIZQDOIl0ZAAABAQDUqh+L5765CGMfSu+pVN0OOJaZ7Te8WrXSSZH2BtGWecNbzEmQ
          lBHE+uW0CJGbpZA7v6r5qLO22tsHKI1VotXEdSF7PGdMWk4JSJlgGikkV2rwV1oYSQFIJk
          mlht1wjZVGrBBCLv2pWziOOXVp0Iz8fPOwW+vyjRpfUOdaiY+gFSiqpP7ldZuzidCIV1p+
          Z3wgzTA9d40/TAtoa8mH2JCFu5S95U80rX69Ma9UvOPnL35uQqW8aRQ7MRKkhBbtzHqkg3
          vj4K5YeEXj7LOq85vu1ExMbwZTknWFYNBbXy3Xb+Fc/+INctxe8iKJ2coHsvEAAvcTymE3
          w8p0pdzp1hadAAAAHWFiZHVsbWFubmFua2hhbjEwMDBAZ21haWwuY29tAQIDBAU=
          -----END OPENSSH PRIVATE KEY-----
        command_timeout: 200m
        script: |
          cd ../..
          cd /var/www/newsisiku-frontend
          git pull origin main
          npm install
          npm run build
          pm2 restart 1
